CREATE DATABASE SCHOOL2;

USE SCHOOL2;

CREATE TABLE TRAINER(
 TRAINER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 TRAINER_FIRST_NAME VARCHAR(30) NOT NULL,
 TRAINER_LAST_NAME VARCHAR(30) NOT NULL,
 TRAINER_SUBJECT VARCHAR(30) NOT NULL
);

